export {default as Footer} from './footer'
export {default as Header} from './header'
export {default as Home} from './home'
export {default as OldProjects} from './oldprojects'
export {default as Contact} from './contact'
export {default as ShowingPage} from './showingpage'